sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - hexo-source
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub
  keep_history: true
  on:
    branch: hexo-source
  local_dir: public
  target_branch: master
