sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - hexo-source
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GitHub
  keep-history: true
  on:
    branch: hexo-source
  local-dir: public
  target_branch: master
